version: "3.8"
name: "cinema-plus-be"
services:
  mongo-express:
    image: mongo-express
    restart: always
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb:27017/$MONGODB_DATABASE?authSource=admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mynetwork
  mongodb:
    container_name: cinema-plus-mongodb
    image: mongo:6.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - db:/data/db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512m
    networks:
      - mynetwork
  app:
    container_name: cinema-plus-api
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
    networks:
      - mynetwork
  
  grafana:
    image: grafana/grafana:8.5.21
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - grafana

  k6:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts
    networks:
      - mynetwork
      - k6
    # Coba test setup
    command:
    - "run"
    - "--out"
    - "influxdb=http://influxdb:8086/k6"
    - "/scripts/load-test.js"
    - "/scripts/spike-test.js"
    - "/scripts/stress-test.js"
    depends_on:
      - app  # Tunggu hingga layanan app selesai dimulai
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6

  # Layanan InfluxDB
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      # - INFLUXDB_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=admin
      # - INFLUXDB_USER_PASSWORD=admin123
    networks:
      - k6
      - grafana


  chronograf:
    image: chronograf:1.8
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=root
      - INFLUXDB_PASSWORD=root
      - INFLUXDB_SKIP_VERIFY=true
    depends_on:
      - influxdb
    networks:
      - k6  

volumes:
  db:
networks:
  mynetwork: 
  k6:
  grafana: